language: java
jdk:
  - oraclejdk8
sudo: false
install: false
cache:
  directories:
    - $HOME/.m2/repository
addons:
  apt:
    update: true
after_success:
  - cd druid-spring-boot-example/druid-spring-boot-mybatis-example
  - mvn clean test -Pcoveralls jacoco:report coveralls:report